# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: jun
  #theme_night: rose
  font: noto
  font_size: M

# SEO

marketing:
  seo:
    site_type: EducationalOrganization
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: 'UA-48444845-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
      - python
      - bash
  math:
    enable: true
  diagram:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true


############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Enter contact details (optional). To hide a field, clear it to "".
email : "nishii [at] yamaguchi-u.ac.jp"
phone : ""
coordinates :
  latitude : "34.1470"
  longitude : "131.4713"

address :
  street: "1677-1"
  city: "Yamaguchi"
  region: "Yamaguchi"
  postcode: "753-8512"
  country: "Japan"
  country_code: "JP"

room : "山口大学吉田キャンパス総合研究棟３０３号室"
room_url : "http://bcl.sci.yamaguchi-u.ac.jp/access"

# Geographic coordinates
coordinates :
  latitude : "34.1470"
  longitude : "131.4713"

# Directions for visitors to locate you.
directions : "Yoshida Research and Education Building 303"

# blog header
reading_time: false